import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,FileText,Briefcase,Images,ShieldCheck,Activity,Download} from 'lucide-react';
import {countCollection,listActivity} from '../services/admin';
export default function Dashboard(){
 const [stats,setStats]=useState({posts:0,projects:0,media:0,messages:0}),[activity,setActivity]=useState([]),[error,setError]=useState('');
 useEffect(()=>{Promise.all(['posts','projects','media','contactMessages'].map(countCollection)).then(([posts,projects,media,messages])=>setStats({posts,projects,media,messages})).catch(e=>setError(e.message));listActivity(8).then(setActivity).catch(()=>{})},[]);
 function exportData(){const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),stats,activity},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-admin-export.json';a.click();URL.revokeObjectURL(a.href)}
 return <div><header className="admin-header"><div><div className="admin-kicker">CONTROL CENTER</div><h1>Dashboard</h1><p>Manage the portfolio without touching the public design.</p></div><button className="admin-secondary compact" onClick={exportData}><Download size={16}/> Export snapshot</button></header>{error&&<div className="admin-error">{error}</div>}<div className="admin-stats"><div><FileText/><b>{stats.posts}</b><span>Posts</span></div><div><Briefcase/><b>{stats.projects}</b><span>Projects</span></div><div><Images/><b>{stats.media}</b><span>Media</span></div><div><ShieldCheck/><b>{stats.messages}</b><span>Contact leads</span></div></div><section className="admin-panel"><div className="panel-heading"><h2>Quick actions</h2><Activity size={18}/></div><div className="admin-actions"><Link to="/admin/posts/new">Create post <ArrowUpRight size={16}/></Link><Link to="/admin/projects/new">Add project <ArrowUpRight size={16}/></Link><Link to="/admin/media">Open media library <ArrowUpRight size={16}/></Link></div></section><section className="admin-panel"><div className="panel-heading"><h2>Recent activity</h2><span>{activity.length} events</span></div><div className="activity-list">{activity.length?activity.map(x=><div className="activity-row" key={x.id}><span>{x.action}</span><b>{x.summary||x.collection}</b><small>{x.createdAt?.toDate?x.createdAt.toDate().toLocaleString():'Recently'}</small></div>):<p className="muted">No activity yet.</p>}</div></section></div>}
